export const continentePorPais = {
  "Abjasia": "Asia",
  "Afganistán": "Asia",
  "Akrotiri y Dhekelia": "Asia",
  "Albania": "Europa",
  "Alemania": "Europa",
  "Alemania Occidental": "Europa",
  "Alemania Oriental": "Europa",
  "Andorra": "Europa",
  "Angola": "África",
  "Anguila": "América",
  "Antigua y Barbuda": "América",
  "Antillas Neerlandesas": "América",
  "Arabia Saudí": "Asia",
  "Argelia": "África",
  "Argentina": "América",
  "Armenia": "Asia",
  "Aruba": "América",
  "Australia": "Oceanía",
  "Austria": "Europa",
  "Austria-Hungría": "Europa",
  "Azerbaiyán": "Asia",
  "Baden": "Europa",
  "Bahamas": "América",
  "Bangladés": "Asia",
  "Barbados": "América",
  "Baréin": "Asia",
  "Baviera": "Europa",
  "Belice": "América",
  "Benín": "África",
  "Bermudas": "América",
  "Bielorrusia": "Europa",
  "Bolivia": "América",
  "Bonaire Sint Eustatius y Saba": "América",
  "Bosnia y Herzegovina": "Europa",
  "Botsuana": "África",
  "Brasil": "América",
  "Brunéi": "Asia",
  "Bulgaria": "Europa",
  "Burkina Faso": "África",
  "Burundi": "África",
  "Bután": "Asia",
  "Bélgica": "Europa",
  "Cabo Verde": "África",
  "Camboya": "Asia",
  "Camerún": "África",
  "Canadá": "América",
  "Catar": "Asia",
  "Chad": "África",
  "Checoslovaquia": "Europa",
  "Chequia": "Europa",
  "Chile": "América",
  "China": "Asia",
  "Chipre": "Europa",
  "Chipre del Norte": "Asia",
  "Colombia": "América",
  "Comoras": "África",
  "Congo": "África",
  "Corea Unida": "Asia",
  "Corea del Norte": "Asia",
  "Corea del Sur": "Asia",
  "Costa Rica": "América",
  "Costa de Marfil": "África",
  "Croacia": "Europa",
  "Cuba": "América",
  "Curazao": "América",
  "Dinamarca": "Europa",
  "Dominica": "América",
  "Dos Sicilias": "Europa",
  "Ecuador": "América",
  "Egipto": "África",
  "El Salvador": "América",
  "Emiratos Árabes Unidos": "Asia",
  "Eritrea": "África",
  "Eritrea y Etiopía": "África",
  "Eslovaquia": "Europa",
  "Eslovenia": "Europa",
  "España": "Europa",
  "Estados Unidos": "América",
  "Estonia": "Europa",
  "Esuatini": "África",
  "Etiopía": "África",
  "Filipinas": "Asia",
  "Finlandia": "Europa",
  "Fiyi": "Oceanía",
  "Francia": "Europa",
  "Gabón": "África",
  "Gambia": "África",
  "Georgia": "Asia",
  "Ghana": "África",
  "Gibraltar": "Europa",
  "Granada": "América",
  "Grecia": "Europa",
  "Groenlandia": "América",
  "Guadalupe": "América",
  "Guam": "Oceanía",
  "Guatemala": "América",
  "Guayana Francesa": "América",
  "Guernsey": "Europa",
  "Guinea": "África",
  "Guinea Ecuatorial": "África",
  "Guinea-Bissau": "África",
  "Guyana": "América",
  "Haití": "América",
  "Hannover": "Europa",
  "Hesse Electoral": "Europa",
  "Hesse Gran Ducal": "Europa",
  "Honduras": "América",
  "Hong Kong": "Asia",
  "Hungría": "Europa",
  "India": "Asia",
  "Indonesia": "Asia",
  "Irak": "Asia",
  "Irlanda": "Europa",
  "Irán": "Asia",
  "Isla Norfolk": "Oceanía",
  "Isla de Man": "Europa",
  "Isla de Navidad": "Asia",
  "Islandia": "Europa",
  "Islas Caimán": "América",
  "Islas Cocos": "Asia",
  "Islas Cook": "Oceanía",
  "Islas Feroe": "Europa",
  "Islas Georgias del Sur y Sandwich del Sur": "América",
  "Islas Malvinas": "América",
  "Islas Marianas del Norte": "Oceanía",
  "Islas Marshall": "Oceanía",
  "Islas Menores Alejadas de los Estados Unidos": "Oceanía",
  "Islas Salomón": "Oceanía",
  "Islas Turcas y Caicos": "América",
  "Islas Vírgenes Británicas": "América",
  "Islas Vírgenes de los Estados Unidos": "América",
  "Islas del Canal": "Europa",
  "Islas Åland": "Europa",
  "Israel": "Asia",
  "Italia": "Europa",
  "Jamaica": "América",
  "Japón": "Asia",
  "Jersey": "Europa",
  "Jordania": "Asia",
  "Kazajistán": "Asia",
  "Kenia": "África",
  "Kirguistán": "Asia",
  "Kiribati": "Oceanía",
  "Kosovo": "Europa",
  "Kuwait": "Asia",
  "Laos": "Asia",
  "Lesoto": "África",
  "Letonia": "Europa",
  "Liberia": "África",
  "Libia": "África",
  "Liechtenstein": "Europa",
  "Lituania": "Europa",
  "Luxemburgo": "Europa",
  "Líbano": "Asia",
  "Macao": "Asia",
  "Macedonia del Norte": "Europa",
  "Madagascar": "África",
  "Malasia": "Asia",
  "Malaui": "África",
  "Maldivas": "Asia",
  "Malta": "Europa",
  "Malí": "África",
  "Marruecos": "África",
  "Martinica": "América",
  "Mauricio": "África",
  "Mauritania": "África",
  "Mayotte": "África",
  "Mecklemburgo-Schwerin": "Europa",
  "Micronesia": "Oceanía",
  "Moldavia": "Europa",
  "Mongolia": "Asia",
  "Montenegro": "Europa",
  "Montserrat": "América",
  "Mozambique": "África",
  "Myanmar": "Asia",
  "México": "América",
  "Módena": "Europa",
  "Mónaco": "Europa",
  "Nagorno-Karabaj": "Asia",
  "Namibia": "África",
  "Nauru": "Oceanía",
  "Nepal": "Asia",
  "Nicaragua": "América",
  "Nigeria": "África",
  "Niue": "Oceanía",
  "Noruega": "Europa",
  "Nueva Caledonia": "Oceanía",
  "Nueva Zelanda": "Oceanía",
  "Níger": "África",
  "Omán": "Asia",
  "Osetia del Sur": "Asia",
  "Pakistán": "Asia",
  "Palaos": "Oceanía",
  "Palestina": "Asia",
  "Panamá": "América",
  "Papúa Nueva Guinea": "Oceanía",
  "Paraguay": "América",
  "Parma": "Europa",
  "Países Bajos": "Europa",
  "Perú": "América",
  "Pitcairn": "Oceanía",
  "Polinesia Francesa": "Oceanía",
  "Polonia": "Europa",
  "Portugal": "Europa",
  "Puerto Rico": "América",
  "Reino Unido": "Europa",
  "República Centroafricana": "África",
  "República Democrática del Congo": "África",
  "República Dominicana": "América",
  "República Popular Democrática de Yemen": "Asia",
  "República de Vietnam": "Asia",
  "República Árabe de Yemen": "Asia",
  "Reunión": "África",
  "Ruanda": "África",
  "Rumania": "Europa",
  "Rusia": "Europa",
  "Sajonia": "Europa",
  "Samoa": "Oceanía",
  "Samoa Americana": "Oceanía",
  "San Bartolomé": "América",
  "San Cristóbal y Nieves": "América",
  "San Marino": "Europa",
  "San Martín (parte francesa)": "América",
  "San Pedro y Miquelón": "América",
  "San Vicente y las Granadinas": "América",
  "Santa Elena": "África",
  "Santa Lucía": "América",
  "Santo Tomé y Príncipe": "África",
  "Senegal": "África",
  "Serbia": "Europa",
  "Serbia excluyendo Kosovo": "Europa",
  "Serbia y Montenegro": "Europa",
  "Seychelles": "África",
  "Sierra Leona": "África",
  "Singapur": "Asia",
  "Sint Maarten": "América",
  "Siria": "Asia",
  "Somalia": "África",
  "Somalilandia": "África",
  "Sri Lanka": "Asia",
  "Sudáfrica": "África",
  "Sudán": "África",
  "Sudán del Sur": "África",
  "Suecia": "Europa",
  "Suiza": "Europa",
  "Surinam": "América",
  "Svalbard y Jan Mayen": "Europa",
  "Sáhara Occidental": "África",
  "Tailandia": "Asia",
  "Taiwán": "Asia",
  "Tanzania": "África",
  "Tayikistán": "Asia",
  "Territorio Británico del Océano Índico": "Asia",
  "Timor": "Asia",
  "Togo": "África",
  "Tokelau": "Oceanía",
  "Tonga": "Oceanía",
  "Toscana": "Europa",
  "Transnistria": "Europa",
  "Trinidad y Tobago": "América",
  "Turkmenistán": "Asia",
  "Turquía": "Asia",
  "Tuvalu": "Oceanía",
  "Túnez": "África",
  "URSS": "Europa",
  "Ucrania": "Europa",
  "Uganda": "África",
  "Uruguay": "América",
  "Uzbekistán": "Asia",
  "Vanuatu": "Oceanía",
  "Vaticano": "Europa",
  "Venezuela": "América",
  "Vietnam": "Asia",
  "Wallis y Futuna": "Oceanía",
  "Wuerttemburg": "Europa",
  "Yemen": "Asia",
  "Yibuti": "África",
  "Yugoslavia": "Europa",
  "Zambia": "África",
  "Zanzíbar": "África",
  "Zimbabue": "África",
};